# Generated by Django 3.2.19 on 2023-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DayProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripdate', models.DateTimeField(verbose_name='date')),
                ('dayprogram', models.CharField(max_length=100)),
                ('actionitems', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Tripper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripper', models.CharField(max_length=100)),
                ('badges', models.ManyToManyField(to='ourtripapp.Badge')),
            ],
        ),
    ]
