# Generated by Django 3.2.19 on 2023-08-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourtripapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='dayprogram',
            name='bookedactivities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dayprogram',
            name='documentsneeded',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dayprogram',
            name='possibleactivities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dayprogram',
            name='task',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dayprogram',
            name='actionitems',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
