# Generated by Django 3.2.19 on 2024-02-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourtripapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayprogram',
            name='part_of_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourtripapp.title'),
        ),
    ]
