# Generated by Django 3.2.19 on 2023-08-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourtripapp', '0002_auto_20230827_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayprogram',
            name='tripdate',
            field=models.DateField(verbose_name='date'),
        ),
    ]
