# Generated by Django 3.2.19 on 2023-08-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourtripapp', '0003_alter_dayprogram_tripdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badgename',
            field=models.CharField(default='badgename', max_length=100),
        ),
    ]
