# Generated by Django 3.2.19 on 2023-08-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourtripapp', '0004_badge_badgename'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayprogram',
            name='dayprogramnumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
