# Generated by Django 3.2.19 on 2023-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourtripapp', '0005_dayprogram_dayprogramnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Trip', max_length=100)),
            ],
        ),
    ]
